### ISSUE TITLE
React warns on giving stateless functional components a ref

### ISSUE THREAD

**Issue by chandlerprall** [chandlerprall/react-insula#5]
Instead of blindly attaching the `ref` attribute, first check to see if the component is a `typeof React.Component`

**Comment by hartzis** [comment]
Nice, i'd also possibly recommend making a new method in `ConnectedComponent` that does the check and can bound in the constructor. Saves it from creating a new instance on each render? :)

https://facebook.github.io/react/docs/refs-and-the-dom.html#caveats

**Comment by chandlerprall** [comment]
Done, thanks for the suggestion!
